---
title: "Forest Inventory and Analysis Species Occurance"
author: "David Marshall, Greg Johnson, Aaron Weiskittel"
date: today
format: pdf
editor: visual
fig-format: png
---


```{r}
#| label: setup_and_data
#| message: false
#| warning: false
#| include: false

library( dplyr )
library( ggplot2 )


states <- c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY")
fips_codes <- c("01", "02", "04", "05", "06", "08", "09", "10", "11", "12", "13", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "44", "45", "46", "47", "48", "49", "50", "51", "53", "54", "55", "56")

state_fips <- data.frame(State = states, STATECD = as.numeric(fips_codes))

data_path <- "F:/Projects/FVS Remodel/data/"

# get species data
x <- read.csv( paste0(data_path, "FIA_TotalLiveTrees_BySpeciesAndState.CSV"), header=T, sep="," )

species_data <- x %>% tidyr::pivot_longer(
    cols = c(2:50), 
    names_to = "state",           
    values_to = "n"  ) %>%
    filter( !is.na(n) )

by_species <- species_data %>% group_by( SPCD, CommonName ) %>% summarize( n = sum(n) ) %>% arrange( desc( n ) )

```


```{r}
#| echo: false
#| message: false
#| warning: false

knitr::kable( by_species, caption = "Observations by Species in FIA Change Dataset")
```

